### ISSUE TITLE
 Segmentation fault: 11

### ISSUE THREAD

**Issue by giantss** [Macielyoung/Confused_Chinese#2]
执行 `python3 fetching.py` 报错了，这个问题咋解决呢？
<img width="440" alt="image" src="https://github.com/user-attachments/assets/cc111848-648a-4431-9275-205750fdc1da">

**Comment by Macielyoung** [comment]
可能是faiss包安装的不正确，重新安装试试，如果跑不成功，data目录下有已经跑好的文件

**Comment by giantss** [comment]
`pip` 安装的 `faiss-cpu` 包有兼容的问题，使用 `conda`安装的就可以了。
